# This workflow will build Speedb on a Mac OS server
#
# This workflow assumes the self hosted runner on a Mac machine is ready.
# The Mac OS server must have all the tools and software required for Speedb building to be installed


name: Build on Ubuntu Arm 

on:
  workflow_call:
    inputs:
      verSion:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuArm64 # a test self hosted runner on a vm with MacOS
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'build'
      run: |
        export SPDB_LIB_DIR=~/spdb_lib &&  mkdir -p $SPDB_LIB_DIR
        docker run --rm -v $(readlink -f ${SPDB_LIB_DIR}):/out -i speedb-centos-builder ${{ github.ref_name }}
    
    - name: 'upload artifacts'    #This step executed only when this workflow is called by another and a version is provided
      if: inputs.verSion != ' '
      run: |
        aws s3 cp ~/spdb_lib/libspeedbjni-linux-aarch64.so s3://spdb-builder/jar_test/v${{ inputs.verSion }}/libspeedbjni-linux-aarch64.so
        mv ~/spdb_lib/libspeedbjni-linux-aarch64.so{,_$(date '+%d_%m_%Y__%H_%M_%S')}